### ISSUE TITLE
OOM Error During Validation Stage in train_middlebury.py

### ISSUE THREAD

**Issue by Crislv7** [Junda24/MonSter#64]
Hi, I am running train_middlebury.py for Middlebury fine-tuning, but the training crashes during the validation stage with a CUDA out-of-memory error.
The error happens around the first validation step, when the model enters test_mode=True:
`disp_pred = model(left, right, iters=cfg.valid_iters, test_mode=True)`

The stack trace shows that the OOM occurs inside the DepthAnythingV2 / DINOv2 ViT attention module:
File "core/monster.py", line 382, in forward
    depth_mono, features_mono_left, features_mono_right = self.infer_mono(image1, image2)
File "core/monster.py", line 348, in infer_mono
    features_left_encoder = self.mono_encoder.get_intermediate_layers(...)
File "Depth-Anything-V2-list3/depth_anything_v2/dinov2_layers/attention.py", line 56, in forward
    attn = attn.softmax(dim=-1)
torch.cuda.OutOfMemoryError: CUDA out of memory.
Tried to allocate around 26-32 GiB on a 44 GB GPU.

My config is similar to:
`encoder: 'vitl'
batch_size: 8
image_size: [352, 896]
train_iters: 20
valid_iters: 32
val_frequency: 20
val_dataset: 'kitti'
num_gpu: 4
`

**Comment by Crislv7** [comment]
After contacting the author, I confirmed that my torch version is 2.0.1 and I am not using EfficientFormer. The issue was resolved by installing the correct version of xformers.
So, if you're facing a similar problem, make sure to install the compatible version of xformers to resolve any efficiency and memory issues.
